name: dnd_character_sheet
description: D&D 5e 2014 character sheet - V0.2
publish_to: "none"
version: 0.2.0+3

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png

flutter_launcher_icons:
  android: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
